# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ef67de23483323832f312841b8600c7f33b44010ed28af3c096ce6cf3c3598767406571801d55c295c478a5fb11e41c00c30f0909fb1b34df40a4d6b373cbda

test:
  secret_key_base: dbed0add950cd2d206e2e89eb9a0e123d1852270c4820432027aea299663eb8ee9a5a277fb0f2f8eb2c3b5014dae85c77b3ba39a97ae96e7bdd77ebbbe5a1c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
